/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hut_InsertionSort */

#ifndef _Included_com_hut_InsertionSort
#define _Included_com_hut_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hut_InsertionSort
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_hut_InsertionSort_sort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
